french_words = [
    {"le": ["the (masculine singular)"]},
    {"de": ["of", "from"]},
    {"un": ["a", "an (masculine singular)"]},
    {"être": ["to be"]},
    {"et": ["and"]},
    {"à": ["to", "at", "in"]},
    {"il": ["he", "it (masculine singular)"]},
    {"avoir": ["to have"]},
    {"ne": ["not"]},
    {"je": ["I"]},
    {"son": ["his", "her", "its"]},
    {"que": ["that", "what"]},
    {"se": ["himself", "herself", "itself"]},
    {"qui": ["who", "whom"]},
    {"ce": ["this", "that"]},
    {"pour": ["for"]},
    {"pas": ["not"]},
    {"sur": ["on", "upon", "over"]},
    {"plus": ["more"]},
    {"pouvoir": ["to be able to", "can"]},
    {"par": ["by", "through", "via"]},
    {"avec": ["with"]},
    {"tout": ["all", "everything"]},
    {"faire": ["to do", "to make"]},
    {"dire": ["to say"]},
    {"devoir": ["to have to", "must"]},
    {"mettre": ["to put", "to place"]},
    {"autre": ["other"]},
    {"on": ["one", "we"]},
    {"mais": ["but"]},
    {"nous": ["we", "us"]},
    {"comme": ["like", "as"]},
    {"si": ["if"]},
    {"leur": ["their"]},
    {"ou": ["or"]},
    {"sans": ["without"]},
    {"si": ["if"]},
    {"alors": ["then", "so"]},
    {"deux": ["two"]},
    {"fois": ["time"]},
    {"bien": ["well", "good"]},
    {"peut": ["can", "may"]},
    {"aussi": ["also", "too"]},
    {"lui": ["him", "her", "it"]},
    {"très": ["very"]},
    {"sous": ["under", "beneath"]},
    {"même": ["same"]},
    {"déjà": ["already"]},
    {"y": ["there"]},
    {"moins": ["less"]},
    {"vouloir": ["to want"]},
    {"grand": ["big", "tall"]},
    {"mon": ["my"]},
    {"dans": ["in", "into"]},
    {"chose": ["thing"]},
    {"voir": ["to see"]},
    {"ni": ["nor"]},
    {"notre": ["our"]},
    {"sans": ["without"]},
    {"quoi": ["what"]},
    {"jour": ["day"]},
    {"fois": ["time"]},
    {"nouveau": ["new"]},
    {"an": ["year"]},
    {"peu": ["few", "little"]},
    {"temps": ["time", "weather"]},
    {"savoir": ["to know"]},
    {"part": ["part"]},
    {"personne": ["person", "nobody"]},
    {"venir": ["to come"]},
    {"suite": ["following", "sequence"]},
    {"main": ["hand"]},
    {"trouver": ["to find"]},
    {"donner": ["to give"]},
    {"vieux": ["old"]},
    {"prendre": ["to take"]},
    {"travail": ["work"]},
    {"petit": ["small", "little"]},
    {"prendre": ["to take"]},
    {"appeler": ["to call"]},
    {"point": ["point"]},
    {"savoir": ["to know"]},
    {"aller": ["to go"]},
    {"année": ["year"]},
    {"encore": ["still", "again"]},
    {"vouloir": ["to want"]},
    {"ensuite": ["then", "next"]},
    {"venir": ["to come"]},
    {"deux": ["two"]},
    {"fois": ["time"]},
    {"très": ["very"]},
    {"jour": ["day"]},
    {"grand": ["big", "tall"]},
    {"nouveau": ["new"]},
    {"main": ["hand"]},
    {"temps": ["time", "weather"]}
]