german_words = [
    {"der": ["the (masculine singular)"]},
    {"die": ["the (feminine singular)", "they"]},
    {"und": ["and"]},
    {"in": ["in", "into"]},
    {"zu": ["to"]},
    {"den": ["the (masculine dative singular)"]},
    {"das": ["the (neuter singular)"]},
    {"mit": ["with"]},
    {"sich": ["oneself", "himself", "herself", "itself", "themselves"]},
    {"des": ["of the (masculine singular genitive)"]},
    {"für": ["for"]},
    {"ist": ["is"]},
    {"auf": ["on", "onto", "at"]},
    {"dass": ["that"]},
    {"ein": ["a", "an (masculine singular)", "one"]},
    {"nicht": ["not"]},
    {"eine": ["a", "an (feminine singular)"]},
    {"als": ["than", "as"]},
    {"auch": ["also", "too"]},
    {"es": ["it"]},
    {"an": ["at", "to", "on"]},
    {"werden": ["to become", "will"]},
    {"aus": ["out of", "from"]},
    {"er": ["he"]},
    {"hat": ["has"]},
    {"nach": ["after", "to", "towards"]},
    {"wird": ["will be"]},
    {"bei": ["by", "at", "with"]},
    {"einer": ["a", "an (feminine singular dative)", "one"]},
    {"einem": ["a", "an (masculine singular dative)", "one"]},
    {"um": ["around", "about"]},
    {"haben": ["to have"]},
    {"einen": ["a", "an (masculine singular accusative)", "one"]},
    {"über": ["above", "over", "about"]},
    {"dieser": ["this", "that (masculine singular nominative)"]},
    {"sie": ["she", "they"]},
    {"noch": ["still", "yet"]},
    {"werden": ["to become", "will"]},
    {"wo": ["where"]},
    {"wir": ["we"]},
    {"mein": ["my", "mine"]},
    {"aus": ["from", "out of"]},
    {"bei": ["at", "by", "with"]},
    {"oder": ["or"]},
    {"wie": ["how", "like", "as"]},
    {"zum": ["to the (masculine singular)"]},
    {"mehr": ["more"]},
    {"doch": ["yet", "but", "after all"]},
    {"nur": ["only", "just"]},
    {"wenn": ["if", "when"]},
    {"man": ["one", "you", "they"]},
    {"sagte": ["said"]},
    {"keine": ["no", "not any"]},
    {"seine": ["his", "its", "their"]},
    {"zeit": ["time"]},
    {"über": ["about", "over", "above"]},
    {"so": ["so", "thus"]},
    {"ihn": ["him", "it"]},
    {"noch": ["still", "yet"]},
    {"aber": ["but", "yet"]},
    {"bis": ["until", "up to"]},
    {"vor": ["before", "in front of"]},
    {"nach": ["after", "according to"]},
    {"nur": ["only", "just"]},
    {"soll": ["shall", "should"]},
    {"unter": ["under", "below", "among"]},
    {"jahr": ["year"]},
    {"seine": ["his", "its", "their"]},
    {"über": ["over", "about"]},
    {"wieder": ["again"]},
    {"ihm": ["to him", "to it"]},
    {"dann": ["then", "at that time"]},
    {"mehr": ["more"]},
    {"uns": ["us", "ourselves"]},
    {"sollte": ["should", "ought to"]},
    {"sei": ["be", "let it be"]},
    {"nichts": ["nothing"]},
    {"dort": ["there"]},
    {"können": ["can", "to be able to"]},
    {"ihr": ["her", "their", "your (formal)"]},
    {"alles": ["everything", "all"]},
    {"waren": ["were"]},
    {"will": ["want", "will"]},
    {"müssen": ["must", "to have to"]},
    {"doch": ["after all", "anyway", "still"]},
    {"ihre": ["her", "their", "your (formal)"]},
    {"zur": ["to the (feminine singular)"]},
    {"zeit": ["time"]},
    {"gegen": ["against", "towards"]},
    {"wurde": ["was", "became"]},
    {"jetzt": ["now"]}
]