mandarin_words = [
    {"的": ["of", "de"]},
    {"是": ["is", "shì"]},
    {"我": ["I", "wǒ"]},
    {"了": ["(completed action marker)", "le"]},
    {"你": ["you", "nǐ"]},
    {"在": ["at", "in", "on", "zài"]},
    {"他": ["he", "tā"]},
    {"我们": ["we", "wǒmen"]},
    {"有": ["have", "yǒu"]},
    {"这": ["this", "zhè"]},
    {"个": ["(measure word)", "gè"]},
    {"好": ["good", "hǎo"]},
    {"来": ["come", "lái"]},
    {"人": ["person", "rén"]},
    {"那": ["that", "nà"]},
    {"得": ["(structural particle)", "de"]},
    {"了": ["(past tense marker)", "le"]},
    {"个": ["(measure word)", "gè"]},
    {"们": ["(plural marker for pronouns)", "men"]},
    {"还": ["still", "hái"]},
    {"可以": ["can", "kěyǐ"]},
    {"就": ["then", "jiù"]},
    {"下": ["down", "xià"]},
    {"和": ["and", "hé"]},
    {"也": ["also", "yě"]},
    {"看": ["look", "kàn"]},
    {"他们": ["they", "tāmen"]},
    {"不": ["not", "bù"]},
    {"想": ["want", "xiǎng"]},
    {"这个": ["this", "zhège"]},
    {"什么": ["what", "shénme"]},
    {"做": ["do", "zuò"]},
    {"上": ["up", "shàng"]},
    {"个": ["(measure word)", "gè"]},
    {"为": ["for", "wèi"]},
    {"吗": ["(question particle)", "ma"]},
    {"能": ["can", "nǐng"]},
    {"去": ["go", "qù"]},
    {"对": ["right", "duì"]},
    {"太": ["too", "tài"]},
    {"和": ["with", "hé"]},
    {"她": ["she", "tā"]},
    {"得": ["get", "děi"]},
    {"也": ["also", "yě"]},
    {"打": ["hit", "dǎ"]},
    {"地": ["ground", "dì"]},
    {"大": ["big", "dà"]},
    {"得": ["must", "děi"]},
    {"而": ["and", "ér"]},
    {"看到": ["see", "kàndào"]},
    {"要": ["want", "yào"]},
    {"让": ["let", "ràng"]},
    {"过": ["pass", "guò"]},
    {"天": ["day", "tiān"]},
    {"都": ["all", "dōu"]},
    {"小": ["small", "xiǎo"]},
    {"门": ["door", "mén"]},
    {"对": ["towards", "duì"]},
    {"些": ["some", "xiē"]},
    {"知道": ["know", "zhīdào"]},
    {"开": ["open", "kāi"]},
    {"见": ["see", "jiàn"]},
    {"告诉": ["tell", "gàosù"]},
    {"爱": ["love", "ài"]},
    {"生活": ["life", "shēnghuó"]},
    {"中": ["in", "zhōng"]},
    {"工作": ["work", "gōngzuò"]},
    {"中": ["middle", "zhōng"]},
    {"好": ["well", "hǎo"]},
    {"一": ["one", "yī"]},
    {"个": ["(general measure word)", "gè"]},
    {"过": ["experience", "guò"]},
    {"里": ["inside", "lǐ"]},
    {"谢谢": ["thank you", "xièxie"]},
    {"像": ["like", "xiàng"]},
    {"为": ["because", "wèi"]},
    {"做": ["make", "zuò"]},
    {"找": ["look for", "zhǎo"]},
    {"事": ["thing", "shì"]},
    {"对": ["to", "duì"]},
    {"时候": ["time", "shíhou"]},
    {"里": ["inside", "lǐ"]},
    {"听": ["listen", "tīng"]},
    {"后": ["after", "hòu"]},
    {"手": ["hand", "shǒu"]},
    {"想要": ["want", "xiǎng yào"]},
    {"就": ["then", "jiù"]},
    {"和": ["(question particle)", "hé"]},
    {"多": ["many", "duō"]},
    {"因为": ["because", "yīnwèi"]},
    {"见": ["meet", "jiàn"]},
    {"说": ["say", "shuō"]},
    {"年": ["year", "nián"]},
    {"能": ["be able to", "néng"]},
    {"所以": ["so", "suǒyǐ"]},
    {"会": ["can", "huì"]},
    {"中": ["among", "zhōng"]}
]