spanish_words = [
    {"el": ["the"]},
    {"de": ["of"]},
    {"que": ["that"]},
    {"y": ["and"]},
    {"a": ["to"]},
    {"en": ["in"]},
    {"un": ["a", "an"]},
    {"ser": ["to be", "be"]},
    {"se": ["reflexive pronoun"]},
    {"no": ["no", "not"]},
    {"haber": ["to have (auxiliary)", "to have", "have"]},
    {"por": ["for", "by"]},
    {"con": ["with"]},
    {"su": ["his", "her", "its", "your (formal)"]},
    {"para": ["for"]},
    {"como": ["like", "as"]},
    {"estar": ["to be", "be"]},
    {"tener": ["to have", "have"]},
    {"le": ["him", "her", "it"]},
    {"lo": ["the (masculine direct object pronoun)", "the", "it (masculine indirect object pronoun)", "it"]},
    {"todo": ["all", "everything"]},
    {"pero": ["but"]},
    {"más": ["more"]},
    {"hacer": ["to do", "do", "to make", "make"]},
    {"o": ["or"]},
    {"poder": ["to be able", "be able", "can"]},
    {"decir": ["to say", "say", "to tell", "tell"]},
    {"este": ["this"]},
    {"ir": ["to go", "go"]},
    {"otro": ["other"]},
    {"ese": ["that"]},
    {"la": ["the (feminine)", "the"]},
    {"si": ["if"]},
    {"me": ["me"]},
    {"ya": ["already"]},
    {"ver": ["to see", "see"]},
    {"porque": ["because"]},
    {"dar": ["to give", "give"]},
    {"cuando": ["when"]},
    {"él": ["he"]},
    {"muy": ["very"]},
    {"sin": ["without"]},
    {"vez": ["time", "instance"]},
    {"mucho": ["a lot", "much"]},
    {"saber": ["to know (information)", "to know", "know"]},
    {"qué": ["what"]},
    {"sobre": ["on", "about"]},
    {"mi": ["my"]},
    {"alguno": ["some"]},
    {"mismo": ["same"]},
    {"yo": ["I"]},
    {"también": ["also", "too"]},
    {"hasta": ["until"]},
    {"año": ["year"]},
    {"dos": ["two"]},
    {"querer": ["to want", "want", "to love", "love"]},
    {"entre": ["between", "among"]},
    {"así": ["like this", "so"]},
    {"primero": ["first"]},
    {"desde": ["from", "since"]},
    {"grande": ["big"]},
    {"eso": ["that"]},
    {"ni": ["neither", "nor"]},
    {"nos": ["us"]},
    {"llegar": ["to arrive", "arrive"]},
    {"pasar": ["to pass", "pass", "to happen", "happen"]},
    {"tiempo": ["time"]},
    {"ella": ["she"]},
    {"sí": ["yes"]},
    {"día": ["day"]},
    {"uno": ["one"]},
    {"bien": ["well"]},
    {"poco": ["little", "few"]},
    {"deber": ["to owe", "owe", "must", "should"]},
    {"entonces": ["then"]},
    {"poner": ["to put", "put", "to place", "place"]},
    {"cosa": ["thing"]},
    {"tanto": ["so much", "too much", "many", "too many"]},
    {"hombre": ["man"]},
    {"parecer": ["to seem", "seem", "to appear", "appear"]},
    {"nuestro": ["our"]},
    {"tan": ["so"]},
    {"donde": ["where"]},
    {"ahora": ["now"]},
    {"parte": ["part"]},
    {"después": ["after", "later"]},
    {"vida": ["life"]},
    {"quedar": ["to stay", "stay", "to remain", "remain"]},
    {"siempre": ["always"]},
    {"creer": ["to believe", "believe"]},
    {"hablar": ["to talk", "talk", "to speak", "speak"]},
    {"llevar": ["to carry", "carry", "to take", "take"]},
    {"dejar": ["to leave", "leave", "to let", "let"]},
    {"nada": ["nothing"]},
    {"cada": ["each", "every"]},
    {"seguir": ["to follow", "follow", "to continue", "continue"]},
    {"menos": ["less", "except"]},
    {"nuevo": ["new"]},
    {"encontrar": ["to find", "find"]},
    {"gente": ["people"]},
    {"general": ["general"]},
]